blank_issues_enabled: false
contact_links:
  - name: 讨论区/功能请求
    url: https://github.com/Programmer-MrWang/SystemTools/discussions/
    about: 若您有新点子或新需求，可以这里求助、询问和征求意见。
  - name: 加入插件 QQ 社群
    url: https://qun.qq.com/universal-share/share?ac=1&authKey=adqll%2FTGElr1mWmmFgsAOf17ZmmJlw3FmaZIPT2DYJ%2FcYh6uayDURTMqzAFvKhkE&busi_data=eyJncm91cENvZGUiOiIxMDc0MjQ0MDkyIiwidG9rZW4iOiJhN0o1LytmMGZMYlkvOUVQUVRtNnFabWIyL2RFcmdqYlBSbnFSTUZjTVVaYXhjSXNSc0IxRjBQd21pTnpVMUpsIiwidWluIjoiMTc4OTY1MjMxMSJ9&data=umJqUvQNJtOglHmrlDJCpxuDwm_qEhJu6YfAN1wnYoNYL4hjsHa-kb6FBRY4tzL5Rpv7uPAzhVCVrnk6Fz0NDQ&svctype=4&tempid=h5_group_info
    about: 在 QQ 群和众多插件开发者以及其它用户交流讨论。（群号：1074244092）
